import { Service, type Context } from "@deepseek-ai/cordis";
import {
  createContributions,
  type Contribution,
} from "../../plugins/contributions";
import type { PluginManager } from "../../plugins/manager";

export const INSTRUCTION_TONES = [
  "slate",
  "red",
  "orange",
  "amber",
  "lime",
  "green",
  "teal",
  "cyan",
  "blue",
  "indigo",
  "purple",
  "pink",
] as const;
export type InstructionTone = (typeof INSTRUCTION_TONES)[number];
export type InstructionCategory = Readonly<{
  id: string;
  title: string;
  tone: InstructionTone;
}>;
export type InstructionModule = Readonly<{
  id: string;
  title: string;
  order: number;
  /** Stable host category preference. Missing contributions use Plugins. */
  category?: string;
  /** Body-only Markdown. Category and item headings are generated by the host. */
  text: string;
}>;
export type SavedModule = Omit<Contribution<InstructionModule>, "id">;
export type InstructionComposition = {
  /** Missing only for retained pre-category compositions. */
  categories?: readonly InstructionCategory[];
  modules: readonly SavedModule[];
  plugins: readonly { id: string; revision: string; enabled: boolean }[];
};
export type SavedInstructions = {
  revision: number;
  composition: InstructionComposition;
  /** Missing only when an older running native host has not migrated yet. */
  inactiveModules?: readonly SavedModule[];
};
export type InstructionDraft = {
  composition: InstructionComposition;
  inactiveModules: readonly SavedModule[];
};
export type InstructionIdentity = { revision: number; sha256: string };
export type InstructionProposal = {
  composition: InstructionComposition;
  error: string | null;
};
export type AgentInstructions = {
  register(module: InstructionModule): void;
  snapshot(): InstructionProposal;
  subscribe(listener: () => void): () => void;
};

export function validInstructionBody(text: string) {
  let fence: "`" | "~" | null = null;
  let previousText = false;
  for (const line of text.split(/\r?\n/u)) {
    const content = line.replace(/^ {0,3}/u, "");
    const marker = content.match(/^(`{3,}|~{3,})/u)?.[1];
    if (marker) {
      const kind = marker[0] as "`" | "~";
      if (fence === kind) fence = null;
      else if (!fence) fence = kind;
      previousText = false;
      continue;
    }
    if (!fence && /^#{1,3}(?:\s|$)/u.test(content)) return false;
    if (!fence && previousText && /^(?:=+|-+)\s*$/u.test(content)) return false;
    if (!fence) previousText = !!content.trim();
  }
  return true;
}

declare module "@deepseek-ai/cordis" {
  interface Context {
    agentInstructions: AgentInstructions;
  }
}

/** Contributions are candidates only. Adoption and execution belong to native control. */
export class AgentInstructionsService
  extends Service
  implements AgentInstructions
{
  private readonly contributions;
  private readonly listeners = new Set<() => void>();
  private state: InstructionProposal = {
    composition: { modules: [], plugins: [] },
    error: "Reading instruction plugins…",
  };
  constructor(ctx: Context, plugins: PluginManager) {
    super(ctx, "agentInstructions");
    this.contributions = createContributions<InstructionModule>(ctx);
    const publish = () => {
      const { configuration, busy, refreshError } = plugins.snapshot();
      const catalog =
        configuration.status === "ready" ? configuration.catalog.plugins : [];
      const modules = this.contributions
        .snapshot()
        .map(({ id: _id, ...module }) => module)
        .sort(
          (a, b) =>
            a.order - b.order || (a.key < b.key ? -1 : a.key > b.key ? 1 : 0),
        );
      const unavailable = catalog.some(
        (plugin) =>
          plugin.enabled &&
          (plugin.error ||
            !ctx.pluginStatus.isActive(plugin.manifest.id, plugin.revision)),
      );
      this.state = {
        composition: {
          categories: DEFAULT_INSTRUCTION_CATEGORIES,
          modules,
          plugins: catalog
            .map((plugin) => ({
              id: plugin.manifest.id,
              revision: plugin.revision,
              enabled: plugin.enabled,
            }))
            .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0)),
        },
        error:
          configuration.status !== "ready" ||
          busy ||
          refreshError ||
          unavailable
            ? "Plugin configuration is incomplete or changing. Resolve plugin errors before applying instructions."
            : !modules.length
              ? "Enable an instruction plugin before applying a base."
              : null,
      };
      for (const listener of this.listeners) listener();
    };
    ctx.effect(() => plugins.subscribe(publish));
    ctx.effect(() => this.contributions.subscribe(publish));
    publish();
  }
  snapshot = () => this.state;
  subscribe = (listener: () => void) => {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  };
  register(module: InstructionModule) {
    if (
      !module ||
      !/^[a-z0-9][a-z0-9._-]{0,79}$/.test(module.id) ||
      typeof module.title !== "string" ||
      !module.title.trim() ||
      /[\r\n\0]/u.test(module.title) ||
      new TextEncoder().encode(module.title).length > 256 ||
      !Number.isInteger(module.order) ||
      module.order < -2147483648 ||
      module.order > 2147483647 ||
      (module.category !== undefined &&
        !DEFAULT_INSTRUCTION_CATEGORIES.some(
          (category) => category.id === module.category,
        )) ||
      typeof module.text !== "string" ||
      module.text.includes("\0") ||
      !validInstructionBody(module.text) ||
      new TextEncoder().encode(module.text).length > 1_048_576
    ) {
      throw new Error(
        "Invalid instruction module: use a bounded id, title, order and UTF-8 text",
      );
    }
    this.contributions.register(this.ctx, {
      id: module.id,
      title: module.title,
      order: module.order,
      category: module.category ?? "plugins",
      text: module.text,
    });
  }
}

export const DEFAULT_INSTRUCTION_CATEGORIES: readonly InstructionCategory[] =
  Object.freeze([
    { id: "core", title: "Core", tone: "purple" },
    { id: "capabilities", title: "Capabilities", tone: "blue" },
    {
      id: "communication",
      title: "Communication Patterns",
      tone: "green",
    },
    { id: "practice", title: "Practice", tone: "orange" },
    { id: "custom", title: "Custom", tone: "amber" },
    { id: "plugins", title: "Plugins", tone: "cyan" },
    { id: "uncategorized", title: "Uncategorized", tone: "slate" },
  ]);
